main_branch_name: main
release_url_template: https://github.com/cladam/tbdflow/releases/tag/{{version}}
stale_branch_threshold_days: 1
monorepo:
  enabled: true
  project_dirs:
    - "plugins"
issue_handling:
  strategy: branch-name
branch_types:
  feature: feature/
  hotfix: hotfix/
  release: release/
  docs: docs/
  chore: chore/
  fix: fix/
  refactor: refactor/
  feat: feat/
  ci: ci/
automatic_tags:
  release_prefix: v
lint:
  conventional_commit_type:
    enabled: true
    allowed_types:
    - build
    - chore
    - ci
    - docs
    - feat
    - fix
    - perf
    - refactor
    - revert
    - style
    - test
  issue_key_missing:
    enabled: false
    pattern: ^[A-Z]+-\d+$
  scope:
    enabled: true
    enforce_lowercase: true
  subject_line_rules:
    max_length: 72
    enforce_lowercase: true
    no_period: true
  body_line_rules:
    max_line_length: 80
    leading_blank: true
