name: Mark Commit as Reviewed

on:
  workflow_dispatch:
    inputs:
      commit_sha:
        description: 'Commit SHA to mark as reviewed'
        required: true
        type: string
      reviewer:
        description: 'Reviewer name (optional)'
        required: false
        type: string
        default: ''

jobs:
  mark-reviewed:
    runs-on: ubuntu-latest
    permissions:
      statuses: write
      contents: read
    
    steps:
      - name: Mark commit as reviewed
        uses: actions/github-script@v7
        with:
          script: |
            const commitSha = '${{ github.event.inputs.commit_sha }}';
            const reviewer = '${{ github.event.inputs.reviewer }}';
            
            // Build description with reviewer if provided
            let description = 'Peer review completed';
            if (reviewer) {
              description += ` by ${reviewer}`;
            }
            
            await github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: commitSha,
              state: 'success',
              context: 'peer-review',
              description: description,
              target_url: `${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/commit/${commitSha}`
            });
            
            console.log(`✓ Marked commit ${commitSha} as reviewed`);