# This workflow publishes the crate to crates.io when a new version tag is pushed.
name: Publish to crates.io

on:
  push:
    # This section configures the workflow to run ONLY on pushes of version tags.
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  publish:
    name: Build, Test & Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
      
      - name: Set git default branch to main
        run: git config --global init.defaultBranch main
      
      # It's good practice to build and test again right before publishing
      - name: Build
        working-directory: ./tbdflow-rs
        run: cargo build --verbose
      
      - name: Run tests
        working-directory: ./tbdflow-rs
        run: cargo test --verbose

      - name: Copy root README to crate folder
        run: cp README.md tbdflow-rs/README.md
      
      - name: Publish to crates.io
        working-directory: ./tbdflow-rs
        run: cargo publish --allow-dirty --token ${{ secrets.CRATES_TOKEN }}
        env:
          # The token is stored in your repository's secrets
          CRATES_TOKEN: ${{ secrets.CRATES_TOKEN }}

