# This workflow publishes the tbdflow-rs crate to crates.io when a new tag is pushed.
name: Publish to crates.io

on:
  push:
    # Pattern matched against refs/tags (e.g., v0.3.0, v1.0.0)
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*' # Matches tags like v0.1.0, v1.0.0, v1.2.3-alpha
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Copy root README to crate folder
        run: cp README.md tbdflow-rs/README.md
      
      - name: Publish to crates.io
        working-directory: ./tbdflow-rs
        run: cargo publish --token ${{ secrets.CRATES_TOKEN }}
        env:
          CRATES_TOKEN: ${{ secrets.CRATES_TOKEN }}
